name: rani_arts
description: A new Flutter application.


publish_to: 'none'
version: 1.0.0+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^0.1.3
  image_picker: ^0.6.7+4
  flutter_staggered_grid_view: ^0.3.1
  firebase_storage: ^3.1.6
  random_string: ^2.0.1
  cloud_firestore: ^0.13.4
#  double_back_to_close_app: ^1.2.0
  flutter_spinkit: ^4.1.2+1
  firebase_auth: ^0.16.1
  flutter_dialogs: ^1.0.4
  flutter_share: ^1.0.2+1
  image_gallery_saver: ^1.5.0
  splashscreen:
  image_downloader: ^0.20.0
  permission_handler: ^5.0.1+1
  fluttertoast: ^7.0.2






dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true


  assets:
    - assets/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
          weight: 900

    - family: Hand
      fonts:
        - asset: fonts/ChelseaMarket-Regular.ttf
          weight: 900

